/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void slider1_change1(GSlider source, GEvent event) { //_CODE_:slider1:589600:
  println("slider1 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:slider1:589600:

public void slider2_change1(GSlider source, GEvent event) { //_CODE_:slider2:894533:
  println("slider2 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:slider2:894533:

public void slider3_change1(GSlider source, GEvent event) { //_CODE_:slider3:256282:
  println("slider3 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:slider3:256282:

public void slider4_change1(GSlider source, GEvent event) { //_CODE_:slider4:754764:
  println("slider4 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:slider4:754764:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Sketch Window");
  slider1 = new GSlider(this, 54, 58, 100, 40, 10.0);
  slider1.setLimits(0.5, 0.0, 1.0);
  slider1.setNumberFormat(G4P.DECIMAL, 2);
  slider1.setOpaque(false);
  slider1.addEventHandler(this, "slider1_change1");
  slider2 = new GSlider(this, 50, 121, 100, 40, 10.0);
  slider2.setLimits(0.5, 0.0, 1.0);
  slider2.setNumberFormat(G4P.DECIMAL, 2);
  slider2.setOpaque(false);
  slider2.addEventHandler(this, "slider2_change1");
  label1 = new GLabel(this, 58, 30, 80, 20);
  label1.setText("My label");
  label1.setOpaque(false);
  label2 = new GLabel(this, 57, 99, 80, 20);
  label2.setText("My label");
  label2.setOpaque(false);
  slider3 = new GSlider(this, 64, 203, 100, 40, 10.0);
  slider3.setLimits(0.5, 0.0, 1.0);
  slider3.setNumberFormat(G4P.DECIMAL, 2);
  slider3.setOpaque(false);
  slider3.addEventHandler(this, "slider3_change1");
  slider4 = new GSlider(this, 58, 278, 100, 40, 10.0);
  slider4.setLimits(0.5, 0.0, 1.0);
  slider4.setNumberFormat(G4P.DECIMAL, 2);
  slider4.setOpaque(false);
  slider4.addEventHandler(this, "slider4_change1");
  label3 = new GLabel(this, 65, 169, 80, 20);
  label3.setText("My label");
  label3.setOpaque(false);
  label4 = new GLabel(this, 67, 251, 80, 20);
  label4.setText("My label");
  label4.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GSlider slider1; 
GSlider slider2; 
GLabel label1; 
GLabel label2; 
GSlider slider3; 
GSlider slider4; 
GLabel label3; 
GLabel label4; 

